apiVersion: v1
kind: Service
metadata:
 labels:
   run: join-accel-service
 name: join-accel-service
spec:
  externalTrafficPolicy: Cluster
  selector:
   app: join-accel-challenge-app
  type: NodePort
  ports:
   - protocol: TCP     
     nodePort: 30000
     port: 3000
     targetPort: 3000
