version: '3'
services:
  accel_div:
    image: join-accel-challenge
    ports:
     - "3002:3002"
    env_file:
     - ./div.env
    environment:
      - production
  accel_diff:
    image: join-accel-challenge
    ports:
     - "3001:3001"
    env_file:
     - ./diff.env
    environment:
      - production
  accel_calc:
    image: join-accel-challenge
    ports:
     - "3000:3000"
    env_file:
     - ./calc.env
    environment:
      - production
    depends_on:
      - accel_div
      - accel_diff
