version: '3.7'
services:
  accel_div:
    image: neoandrey/join-accel-challenge
    ports:
     - "3002:3002"
    env_file:
     - ./div.env
    environment:
      - production
  accel_diff:
    image: neoandrey/join-accel-challenge
    ports:
     - "3001:3001"
    env_file:
     - ./diff.env
    environment:
      - production
  accel_calc:
    image: neoandrey/join-accel-challenge
    ports:
     - "3000:3000"
    env_file:
     - ./calc.env
    environment:
      - production
    depends_on:
      - accel_div
      - accel_diff
  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
       - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
